import type { PersonalityConfig, ModeId } from '../types/personality';

export const PERSONALITY_CONFIGS: Record<ModeId, PersonalityConfig> = {
  vibe_check: {
    mode: 'vibe_check',
    archetype: 'spark_reader',
    tone_keywords: ['terse', 'flirty', 'fast', 'punchy', 'provocative'],
    max_question_words: 15,
    max_option_words: 3,
    follow_up_probability: 0.0,
    vulnerability_ceiling: 0.15,
    pacing_ms: 30000,
    activities_allowed: [],
    question_pool_tags: ['humor', 'attraction', 'preferences', 'energy'],
    wrap_type: 'flash',
    memory_depth: 0,
    session_duration_range: [5, 10],
    text_input_ratio: 0.0,
    voice_input_enabled: false,
  },

  first_date: {
    mode: 'first_date',
    archetype: 'curious_stranger',
    tone_keywords: ['warm', 'curious', 'playful', 'genuine', 'gradual'],
    max_question_words: 25,
    max_option_words: 8,
    follow_up_probability: 0.3,
    vulnerability_ceiling: 0.45,
    pacing_ms: 60000,
    activities_allowed: ['twoTruths'],
    question_pool_tags: ['values', 'dreams', 'humor', 'personality', 'past', 'future'],
    wrap_type: 'first_impressions',
    memory_depth: 0,
    session_duration_range: [20, 30],
    text_input_ratio: 0.1,
    voice_input_enabled: false,
  },

  date_night: {
    mode: 'date_night',
    archetype: 'instigator',
    tone_keywords: ['balanced', 'playful', 'deep', 'intimate', 'referential'],
    max_question_words: 30,
    max_option_words: 10,
    follow_up_probability: 0.5,
    vulnerability_ceiling: 0.8,
    pacing_ms: 75000,
    activities_allowed: ['twoTruths', 'finishSentence', 'playlist'],
    question_pool_tags: ['values', 'dreams', 'conflict', 'past', 'future', 'attraction', 'humor'],
    wrap_type: 'briefing',
    memory_depth: 5,
    session_duration_range: [30, 45],
    text_input_ratio: 0.2,
    voice_input_enabled: false,
  },

  ldr: {
    mode: 'ldr',
    archetype: 'bridge_builder',
    tone_keywords: ['intimate', 'present', 'deliberate', 'sensory', 'tender'],
    max_question_words: 35,
    max_option_words: 10,
    follow_up_probability: 0.8,
    vulnerability_ceiling: 0.9,
    pacing_ms: 90000,
    activities_allowed: ['finishSentence', 'playlist'],
    question_pool_tags: ['values', 'dreams', 'distance', 'future', 'sensory', 'longing'],
    wrap_type: 'distance',
    memory_depth: 5,
    session_duration_range: [30, 40],
    text_input_ratio: 0.3,
    voice_input_enabled: true,
  },

  reignite: {
    mode: 'reignite',
    archetype: 'provocateur',
    tone_keywords: ['challenging', 'surprising', 'irreverent', 'loving', 'provocative'],
    max_question_words: 25,
    max_option_words: 8,
    follow_up_probability: 0.6,
    vulnerability_ceiling: 0.95,
    pacing_ms: 70000,
    activities_allowed: ['finishSentence'],
    question_pool_tags: ['conflict', 'past', 'growth', 'attraction', 'rediscovery', 'challenge'],
    wrap_type: 'reconnaissance',
    memory_depth: 10,
    session_duration_range: [20, 40],
    text_input_ratio: 0.2,
    voice_input_enabled: true,
  },
};
